### ISSUE TITLE
Conda forge may be required in the environment file

### ISSUE THREAD

**Issue by rogerkuou** [RS-DAT/JupyterDaskOnSLURM#12]
I see in [this commit](https://github.com/RS-DAT/JupyterDaskOnSLURM/commit/86f62c5f1a771f7c8c070f5ff6be5ea38833d99c), the channel constraint is removed from `environment.yaml`:

```yaml
channels:
  - conda-forge
```

When testing the environment set up on Spider, the following error is poped:

```
(base) [caroline-oku@ui-01 JupyterDaskOnSLURM]$ mamba env create -f environment.yaml
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change


Looking for: ['python=3.9', 'dask', 'dask-jobqueue', "jupyterlab[version='>=3']", 'dask-labextension', 'pip']


Encountered problems while solving:
  - nothing provides requested dask-labextension
```

This error can be fixed by adding back the conda forge channel constraint. I am not sure if this is the essential cause though.

**Comment by fnattino** [comment]
You are probably right, it would be better to leave the channel in. 

If one follows strictly the documentation here and installs `mambaforge` (or `miniforge`), the only channel that is setup is conda-forge, so the issue does not arise. But problems might occur if one uses other `conda`/`mamba` installers.
