### ISSUE TITLE
Description on giving excution rights

### ISSUE THREAD

**Issue by rogerkuou** [RS-DAT/JupyterDaskOnSLURM#8]
When cloning this repo to Snellius/Spider, by default the Slurm job files for running Jupyter servr, i.e. `jupyter_dask_snellius.bsh` and `jupyter_dask_spider.bsh` do not have execution rights.

Maybe we can add instruction on changing the rights? For example:

```sh
chmod a+x scripts/*.bsh
```

**Comment by fnattino** [comment]
Do we actually need execution rights for these scripts? Don't we only have to submit them to SLURM via: `sbatch scripts/jupyter_dask_spider.bsh` ?

**Comment by rogerkuou** [comment]
@fnattino Ah you are right! I think when I first tried this I got some other issue and I thought it is the execution right. Just confirmed it can be submitted without execution right. will close this one.
